apiVersion: v1
kind: Service
metadata:
  name: my-java-app-push
  namespace: myapp-push
spec:
  type: LoadBalancer
  selector:
    app: my-java-app-push
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080